export const CREATE_NEW_CALENDAR_EVENT = 'CREATE_NEW_CALENDAR_EVENT';
export const DELETE_CALENDAR_EVENT = 'DELETE_CALENDAR_EVENT';
export const SET_DATE_TO_TODAY = 'SET_DATE_TO_TODAY';
export const SWITCH_TO_A_MONTH_AGO = 'SWITCH_TO_A_MONTH_AGO';
export const SWITCH_TO_ONE_MONTH_FORWARD = 'SWITCH_TO_ONE_MONTH_FORWARD';
export const SHOW_HIDE_SIDEBAR = 'SHOW_HIDE_SIDEBAR';